version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_USER: vehicle
      POSTGRES_PASSWORD: vehicle
      POSTGRES_DB: vehicle
    ports:
      - "5432:5432"
    networks:
      - vehicle-network
    restart: unless-stopped

  app:
    build: ./vehicule-server
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://vehicle:vehicle@db:5432/vehicle
    networks:
      - vehicle-network
    depends_on:
      - db
    restart: unless-stopped

  cli:
    build: .
    ports:
      - "8080:8080"
    networks:
      - vehicle-network

networks:
  vehicle-network:
    driver: bridge