version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_USER: vehicle
      POSTGRES_PASSWORD: vehicle
      POSTGRES_DB: vehicle
    ports:
      - "5432:5432"
    networks:
      - vehicle-network
    restart: unless-stopped

  app:
    build: ./vehicule-server
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: vehicle
      DB_USER: vehicle
      DB_PASSWORD: vehicle
      PORT: 3001
    networks:
      - vehicle-network
    depends_on:
      - db
    restart: unless-stopped

  cli:
    build: .
    tty: true
    environment:
    - API_HOST=app
    ports:
      - "8080:8080"
    stdin_open: true
    networks:
      - vehicle-network
    depends_on:
      - app

networks:
  vehicle-network:
    driver: bridge